apiVersion: v1
kind: Pod
metadata:
  name: erase-una-vez-1
  labels:
    name: erase-una-vez-1
spec:
  containers:
  - name: erase-una-vez-1
    image: ghcr.io/mmorejon/erase-una-vez-1:v0.3.0
    resources:
      limits:
        memory: 128Mi
        cpu: 500m
